// <auto-generated />
using System;
using CourseSuggestApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseSuggestApi.Data.Migrations
{
    [DbContext(typeof(SuggestDbContext))]
    [Migration("20181127111037_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("CourseSuggestApi.Data.Model.AbilityLevel", b =>
                {
                    b.Property<int>("AbilityLevelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("AbilityLevelId");

                    b.ToTable("AbilityLevels");
                });

            modelBuilder.Entity("CourseSuggestApi.Data.Model.CourseSuggestion", b =>
                {
                    b.Property<int>("CourseSuggestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AbilityLevelId");

                    b.Property<string>("AuthorLevel");

                    b.Property<string>("AuthorName");

                    b.Property<string>("AuthorRole");

                    b.Property<string>("CourseDescription");

                    b.Property<string>("CourseName");

                    b.Property<int?>("DeliveryMethodId");

                    b.HasKey("CourseSuggestionId");

                    b.HasIndex("AbilityLevelId");

                    b.HasIndex("DeliveryMethodId");

                    b.ToTable("CourseSuggestions");
                });

            modelBuilder.Entity("CourseSuggestApi.Data.Model.DeliveryMethod", b =>
                {
                    b.Property<int>("DeliveryMethodId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("DeliveryMethodId");

                    b.ToTable("DeliveryMethods");
                });

            modelBuilder.Entity("CourseSuggestApi.Data.Model.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseSuggestionId");

                    b.Property<string>("VoterId");

                    b.HasKey("VoteId");

                    b.HasIndex("CourseSuggestionId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("CourseSuggestApi.Data.Model.CourseSuggestion", b =>
                {
                    b.HasOne("CourseSuggestApi.Data.Model.AbilityLevel", "AbilityLevel")
                        .WithMany()
                        .HasForeignKey("AbilityLevelId");

                    b.HasOne("CourseSuggestApi.Data.Model.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId");
                });

            modelBuilder.Entity("CourseSuggestApi.Data.Model.Vote", b =>
                {
                    b.HasOne("CourseSuggestApi.Data.Model.CourseSuggestion", "Suggestion")
                        .WithMany()
                        .HasForeignKey("CourseSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
