// <auto-generated />
using System;
using CourseSuggestApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseSuggestApi.Db.Migrations
{
    [DbContext(typeof(SuggestDbContext))]
    partial class SuggestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("CourseSuggestApi.Db.Model.AbilityLevel", b =>
                {
                    b.Property<int>("AbilityLevelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("AbilityLevelId");

                    b.ToTable("AbilityLevels");
                });

            modelBuilder.Entity("CourseSuggestApi.Db.Model.CourseSuggestion", b =>
                {
                    b.Property<int>("CourseSuggestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AbilityLevelId");

                    b.Property<string>("AuthorLevel");

                    b.Property<string>("AuthorName");

                    b.Property<string>("AuthorRole");

                    b.Property<string>("CourseDescription");

                    b.Property<string>("CourseName");

                    b.Property<bool>("IsRunningCourse");

                    b.HasKey("CourseSuggestionId");

                    b.HasIndex("AbilityLevelId");

                    b.ToTable("CourseSuggestions");
                });

            modelBuilder.Entity("CourseSuggestApi.Db.Model.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseSuggestionId");

                    b.Property<string>("VoterId");

                    b.HasKey("VoteId");

                    b.HasIndex("CourseSuggestionId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("CourseSuggestApi.Db.Model.CourseSuggestion", b =>
                {
                    b.HasOne("CourseSuggestApi.Db.Model.AbilityLevel", "AbilityLevel")
                        .WithMany()
                        .HasForeignKey("AbilityLevelId");
                });

            modelBuilder.Entity("CourseSuggestApi.Db.Model.Vote", b =>
                {
                    b.HasOne("CourseSuggestApi.Db.Model.CourseSuggestion", "Suggestion")
                        .WithMany("Votes")
                        .HasForeignKey("CourseSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
